### ISSUE TITLE
Question: Live Reload & Delve debugging

### ISSUE THREAD

**Issue by ivorscott** [githubnemo/CompileDaemon#40]
I am using VSCode and Docker. I want to live reload a go api and use the delve debugger in the same container instance.

Here's what I have so far: https://github.com/ivorscott/go-delve-reload

In the docker-compose.yml file you will see two services api and debug api. One uses CompileDaemon, the other uses Delve. Both containers are based off the same "dev" build stage in a multi-stage scenario. 

Whenever I tried combining both approaches within one container I had issues. Ideally I want to have both features in one container.

**Comment by ahhmarr** [comment]
did you manage to solve the issue?

**Comment by aligator** [comment]
I got it working. 
the problem is that it doesn't kill delve properly and therefore each re-run starts a new instance.

To prevent that, just pass  `--graceful-kill` and it will kill the debugger propperly:


```yaml
app:
    command: --build="go build -o /code/App /code/app.go" --graceful-kill --command="dlv exec --accept-multiclient --continue --headless --listen=:2345 --api-version=2 /code/App"
    ports:
      - 2345:2345
    build:
      dockerfile: dev.Dockerfile
      context: .
    volumes:
      - ./:/code
```

```
....

RUN go mod download && go mod verify && \
    mkdir -p /code/images && \
    go install github.com/go-delve/delve/cmd/dlv@latest && \
    go install github.com/githubnemo/CompileDaemon@latest

ENV GOOS linux
ENV GOARCH amd64

# port 2345 -> debugger port
EXPOSE 2345

ENTRYPOINT ["CompileDaemon"]
```
