### ISSUE TITLE
Reload not working on OSX 

### ISSUE THREAD

**Issue by paologf-mb** [githubnemo/CompileDaemon#47]
I'm setting up a project in Go following this guide https://levelup.gitconnected.com/how-to-live-reload-code-for-golang-and-docker-without-third-parties-ee90721ef641 , on Linux it works fine. Using it from mac when I change a file from my editor, the file into the container change but CompileDaemon doesn't recognise the change and doesn't rebuild. 
If I enter the container and save the changed file, CompileDaemon rebuild.

DOCKER FILE
```
FROM golang:latest

WORKDIR /go/src
```

DockerCompose
```
version: '3'
services:
  app:
    build:
      context: .
    volumes:
      - ".:/go/"
    container_name: golang_app
    command: bash -c "go get github.com/githubnemo/CompileDaemon && CompileDaemon -command="./app""
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      - db
```

VERSIONs
```
OSX Catalina 10.15.2
Docker version 19.03.5 ( Using Docker Desktop application)
```
